# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb7f3c7c75683e24475f46a2040ccd6c5dc167879e33c41948295cebecabc0d2122f020010e5f8b8caa80a9840f93190b8121dcfbc9514493594492e512986fa

test:
  secret_key_base: aba931e39b6bf9ff7319bb3baef5dd2b218c8a8af2dd39c1f618f157f25d30ce96649b3583f82459bab76cf50559eeb702acab905c92ca8383e81a2fbf848ac4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
